language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
  - '9'
  - '10'
before_install:
- npm install -g npm
- npm install -g greenkeeper-lockfile@1
install: npm install
before_script:
  - greenkeeper-lockfile-update
  - npm --v
script: 
  - npm test
after_script: greenkeeper-lockfile-upload
after_success:
  - npm run report-coverage
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
